import { ReactNode } from 'react'
import Head from 'next/head'
import SideBar from './Sidebar'

interface LayoutProps {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  return (
    <div className="reactive min-h-screen flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar></SideBar>
      <main className="justify-center flex w-full">{children}</main>
    </div>
  )
}
